host:        "localhost"
port:        4222
server_name: "bench-server"

jetstream {
  store_dir:        "./nats_data"
  max_memory_store: 1GB
  max_file_store:   10GB

  # 不强制 fsync（对齐 Kafka 默认行为）
  # sync_interval: "2m"    ← 默认值，2分钟才 fsync 一次
}
