server_name: "n3-c1"
listen: "127.0.0.1:4224"

jetstream: {
  store_dir: "./storage/n3"
}

cluster: {
  name: "C1"
  listen: "0.0.0.0:6224"
  routes: [
    "nats-route://127.0.0.1:6222"
    "nats-route://127.0.0.1:6223"
  ]
}
