server_name: "n1-c1"
listen: "127.0.0.1:4222"

jetstream: {
  store_dir: "./storage/n1"
}

cluster: {
  name: "C1"
  listen: "0.0.0.0:6222"
  routes: [
    "nats-route://127.0.0.1:6223"
    "nats-route://127.0.0.1:6224"
  ]
}
