server_name: "n2-c1"
listen: "127.0.0.1:4223"

jetstream: {
  store_dir: "./storage/n2"
}

cluster: {
  name: "C1"
  listen: "0.0.0.0:6223"
  routes: [
    "nats-route://127.0.0.1:6222"
    "nats-route://127.0.0.1:6224"
  ]
}
