server_name: "leaf2"
listen: "192.168.198.128:5224"

jetstream: {
  store_dir: "./storage/leaf2"
  domain: "leaf2"
}

leafnodes {
  remotes = [
    {
      url: "nats://10.169.108.55:7423"
    }
  ]
}