server_name: "leaf1"
listen: "192.168.198.128:5223"

jetstream: {
  store_dir: "./storage/leaf1"
  domain: "leaf1"
}

leafnodes {
  remotes = [
    {
      url: "nats://10.169.109.132:7422"
    }
  ]
}