server_name: "leaf3"
listen: "192.168.198.128:5225"

jetstream: {
  store_dir: "./storage/leaf3"
  domain: "leaf3"
}

leafnodes {
  remotes = [
    {
      url: "nats://10.169.108.55:7424"
    }
  ]
}