###############################################
# 实验室 Hub Cluster - Node 3
###############################################

server_name: "lab-hub-3"
listen: "10.169.108.55:4224"

#──────────────────────────────
# JetStream
#──────────────────────────────
jetstream {
  store_dir: "/root/data/nats/hub-3"
  domain: "lab-hub"
  max_memory_store: 1GB
  max_file_store: 10GB
}

#──────────────────────────────
# Cluster
#──────────────────────────────
cluster {
  name: "lab-hub-cluster"
  listen: "10.169.108.55:6224"
  routes: [
    "nats-route://10.169.108.55:6222"
    "nats-route://10.169.108.55:6223"
  ]
}

#──────────────────────────────
# Leaf Node 监听
#──────────────────────────────
leafnodes {
    remotes = [
    {
      url: "nats://10.169.108.55:7424"
    }
  ]
}