###############################################
# 实验室 Hub Cluster - Node 1
###############################################

server_name: "lab-hub-1"
listen: "10.169.108.55:4222"  # 目前模拟阶段暂无其他服务器

#──────────────────────────────
# JetStream
#──────────────────────────────
jetstream {
  store_dir: "/root/data/nats/hub-1"
  domain: "lab-hub"
  max_memory_store: 1GB
  max_file_store: 10GB
}

#──────────────────────────────
# Cluster
#──────────────────────────────
cluster {
  name: "lab-hub-cluster"
  listen: "10.169.108.55:6222"
  routes: [
    "nats-route://10.169.108.55:6223"
    "nats-route://10.169.108.55:6224"
  ]
}

#──────────────────────────────
# Leaf Node 监听
#──────────────────────────────
leafnodes {
    remotes = [
    {
      url: "nats://10.169.108.55:7422"
    }
  ]
}