server_name: "n3-c1"
listen: "192.168.198.128:5224"

# jetstream: {
#   store_dir: "./storage/n3"
#   domain: "leaf3"
# }

leafnodes {
  remotes = [
    {
      url: "nats://10.169.108.55:7422"
    }
  ]
}
