server_name: "n2-c1"
listen: "192.168.198.128:5223"

# jetstream: {
#   store_dir: "./storage/n2"
#   domain: "leaf2"
# }

leafnodes {
  remotes = [
    {
      url: "nats://10.169.108.55:7422"
    }
  ]
}